name: nitsche_corners

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        pip install scikit-fem==1.0.0 jupyter matplotlib

    - name: Run notebook
      env:
        NREFS: 0
      run: |
        jupyter nbconvert --to notebook --execute nitsche_corners.ipynb
        sh extract.sh

    - uses: actions/upload-artifact@v2
      with:
        name: ex1
        path: ex1*
